### ISSUE TITLE
Share my experience of successfully running the test code for Mamba2 based on the CUDA 11.8

### ISSUE THREAD

**Issue by poult-lab** [state-spaces/mamba#718]
Hello, fellow researchers,

Mamba2 was released one year ago, and the Mamba architecture is a highly effective method for downstream tasks. Therefore, I decided to deploy the upgraded version of Mamba, called Mamba2. I would like to share my experience with the installation of Mamba2, as its procedure is quite sophisticated.

My environment:
python(3.10)
CUDA(11.8)
Pytorch(2.1.1)
mamba_ssm(2.0.3)
causal_conv1d(1.5.0.post8)

The procedure as below:
1.you can try to build a conda environment via below code
```
conda create -n mamba2 python=3.10 anaconda
```

2.install Pytorch, torchvision, torchaudio, pytorch-cuda from [here](https://pytorch.org/get-started/previous-versions/), and then install. here we have to istall the 2.1.1 of Pytorch, otherwise, the error will occur: ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```
conda install pytorch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 pytorch-cuda=11.8 -c pytorch -c nvidia
```

3.install mamba_ssm(2.0.3) from [here](https://github.com/state-spaces/mamba/releases), otherwise, another error will be occurred:_ZN3c107WarningC1ENS_7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEEERKNS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb
```
pip install mamba_ssm-2.0.3+cu118torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
```

4.install the causal_conv1d from [here](https://github.com/Dao-AILab/causal-conv1d/releases), otherwise, the error will occur AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'
```
pip install causal_conv1d-1.5.0.post8+cu11torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
```

5.and the last, below is the test code 
```
from mamba_ssm import Mamba2
import torch

batch, length, dim = 2, 64, 384
x = torch.randn(batch, length, dim).to("cuda")
model = Mamba2(
    # This module uses roughly 3 * expand * d_model^2 parameters
    d_model=dim, # Model dimension d_model
    d_state=64,  # SSM state expansion factor, typically 64 or 128
    d_conv=4,    # Local convolution width
    expand=2,    # Block expansion factor
    headdim=48,
).to("cuda")
y = model(x)
assert y.shape == x.shape
```
6.please use the below code to downgrade the Numpy if you are encountering this warning.
```
pip install 'numpy<2'
```
```
/home/msdl/anaconda3/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181202/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

```

Since I'm using CUDA 11.8, I encountered these issues. It might work fine if you're using CUDA 12. You can use the code below to install it.
```
pip install mamba-ssm[causal-conv1d]
```

**Comment by thomascong121** [comment]
Thanks, this is really helpful, I wander if it will work with CUDA11.6.

**Comment by poult-lab** [comment]
> Thanks, this is really helpful, I wander if it will work with CUDA11.6.

I am not sure, as I only tried with CUDA 11.8.

**Comment by FUGUILuo** [comment]
Is this approach limited by the glibc version?

**Comment by poult-lab** [comment]
> glibc version
hello friend
I have not encountered the problem regarding the glibc version.

**Comment by FUGUILuo** [comment]
> > glibc 版本
> > 你好朋友，
> > 我没有遇到过关于 glibc 版本的问题。

Could you please tell me your system's GLIBC version?

You can check it by running the command: `ldd --version`

**Comment by poult-lab** [comment]
> > > glibc 版本
> > > 你好朋友，
> > > 我没有遇到过关于 glibc 版本的问题。
> 
> Could you please tell me your system's GLIBC version?
> 
> You can check it by running the command: `ldd --version`

Hello folk, 
Sorry for the late reply. 
below is my system's GLIBC version

ldd (Ubuntu GLIBC 2.35-0ubuntu3.11) 2.35
Copyright (C) 2022 自由软件基金会。
这是自由软件；复制本软件需满足的条件请参见源代码。本软件不提供任何
品质保证；甚至不保证适销性或是适用于某种特定用途。
由 Roland McGrath 和 Ulrich Drepper 编写。

**Comment by VincentX324** [comment]
Do I absolutely have to use Linux to download Mamba?

**Comment by poult-lab** [comment]
> Do I absolutely have to use Linux to download Mamba?

I am not sure, but I recommend using Mamba on a Linux-based system.
